### ISSUE TITLE
Path for luau-lsp.types.definitionFiles doesn't work on Windows

### ISSUE THREAD

**Issue by mikejohnstn** [JohnnyMorganz/luau-lsp#78] opened 2022-07-16 04:28 UTC
I'm successfully using `luau-lsp.types.definitionFiles` on macOS to define my own types with an absolute path to a definition file. Unfortunately I can't get the same definitions to work on Windows though. On reload, luau-lsp simply says the definitions file does not exist.

I'm pretty sure I've tried all combinations and permutations of forward slashes, backward slashes, double slashes, double quotes, etc. I've also tried both using the VSCode Settings UI and editing the json manually.

I'm also sure the file exists at the path I'm providing! Not sure what else it could be.

**Comment by JohnnyMorganz** [comment] 2022-07-16 07:57
Strange, in the error message, does that path look correct that it says it can't find? 

One thing to try is to potentially use a relative path from your workspace root. Also, try copying the file over into your workspace and use a relative path for that.

If the latter works, one potential issue that I'm possibly thinking is that VSCode is not happy reading files outside of your workspace for some reason

**Comment by JohnnyMorganz** [comment] 2022-07-16 12:35
Was able to reproduce this - it looks like relative file paths work, but absolute ones don't

**Comment by JohnnyMorganz** [comment] 2022-07-16 12:59
Fixed in https://github.com/JohnnyMorganz/luau-lsp/commit/3e96126c13c8fb19fa1aab12baf422e93e8aeb37

**Closed by JohnnyMorganz** 2022-07-16 12:59 UTC
Labels: bug

**Comment by mikejohnstn** [comment] 2022-07-18 02:01
Confirmed, cheers.
