### ISSUE TITLE
"Failed to load sourcemap.json" error even in scratch rojo workspace

### ISSUE THREAD

**Issue by xcosanxc** [JohnnyMorganz/luau-lsp#849] opened 2024-11-30 14:35 UTC
This error occurs when luau-lsp is reloaded
(Trace: Verbose) Output log:
[OutputLog.txt](https://github.com/user-attachments/files/17965694/message.1.txt)

Versions:
Vscode v1.95.3
Luau-lsp v1.35.0
Rojo v2.1.2

**Comment by JohnnyMorganz** [comment] 2024-12-14 12:39
Unfortunately this is due to the non-ASCII characters in your file path.

Duplicate of #746

**Closed by JohnnyMorganz** 2024-12-14 12:39 UTC
