### ISSUE TITLE
Typechecker reports false positives when defining a user-defined type in the project

### ISSUE THREAD

**Issue by JBai34** [JohnnyMorganz/luau-lsp#251] opened 2022-12-21 18:18 UTC
Defining function return type will raise type-related errors.

For example, adding a user-defined return type (such as Roact.Element) will raise an error of _unknown type_.
<img width="529" alt="Screenshot 2022-12-21 at 14 13 43" src="https://user-images.githubusercontent.com/101073582/208975270-d962ff11-d0e9-4ee3-8f71-dee24f204e59.png">

**Comment by JohnnyMorganz** [comment] 2022-12-28 17:47
I can't reproduce this issue, make sure the module `Roact` has an exported type binding `Element`

**Comment by JohnnyMorganz** [comment] 2023-01-06 17:34
Going to close this as I can't reproduce. Feel free to reopen if you still have problems

**Closed by JohnnyMorganz** 2023-01-06 17:34 UTC
