### ISSUE TITLE
should understand script.Name form in init.lua

### ISSUE THREAD

**Issue by matthargett** [JohnnyMorganz/luau-lsp#116] opened 2022-08-29 17:27 UTC
in init.lua files, you can specify the script names in the directory like this:
```lua
-- packages/shared/Foo.lua
```

```lua
-- packages/shared/init.lua
local _ = requite(script.Foo)
```

LSP doesn't trace these requires correctly:
<img width="821" alt="image" src="https://user-images.githubusercontent.com/1550766/187261640-edd526ef-04fd-49d5-bb56-b2baf75473d3.png">

**Comment by JohnnyMorganz** [comment] 2022-08-29 18:58
I can't reproduce this, it works correctly for me
![image](https://user-images.githubusercontent.com/19635171/187277127-b262c272-01bf-4d90-b7bc-624423e54ba0.png)
![image](https://user-images.githubusercontent.com/19635171/187277157-66a0bc3f-849a-4c50-9036-17fe199ed922.png)

**Comment by JohnnyMorganz** [comment] 2022-09-04 16:40
Going to close this as I cannot reproduce. If you have this issue again, let me know

**Closed by JohnnyMorganz** 2022-09-04 16:40 UTC
