### ISSUE TITLE
Support for Sublime Text

### ISSUE THREAD

**Issue by badcc** [JohnnyMorganz/luau-lsp#79] opened 2022-07-20 17:12 UTC
In-repo support for Sublime Text, like the VS Code plugin, would be amazing! I think it would not be too difficult to add basic support. Thanks!

**Comment by JohnnyMorganz** [comment] 2022-07-20 18:44
Duplicate of #50

I definitely want it though! I've never used sublime text so I plan to look into it one day when I'm free.

It would be great if anyone interested could potentially contribute a starting point to using it in sublime text. I'm happy to maintain it from there. Otherwise I will try to get to it some time.

**Closed by JohnnyMorganz** 2022-07-20 18:44 UTC

**Comment by badcc** [comment] 2022-07-20 18:48
Sounds good thanks!
