### ISSUE TITLE
Luau LSP doesn't respect relativeToRequire setting when first opening a file

### ISSUE THREAD

**Issue by SolarHorizon** [JohnnyMorganz/luau-lsp#484] opened 2023-11-02 16:01 UTC
When first opening a luau file, Luau LSP seems to start in relativeToWorkspaceRoot mode, even though I've got it set to relativeToRequire. It also doesn't seem to be respecting directory aliases. After I make changes to the file (even without saving), it starts working correctly.

This happens both in Neovim (as seen below) and in VSCode.

https://github.com/JohnnyMorganz/luau-lsp/assets/23710811/940bdcf9-3b7c-4136-a070-f273721cb0e2

**Comment by JohnnyMorganz** [comment] 2023-11-04 14:37
This is a known issue. The problem here is that we don't receive user settings immediately, so diagnostics start running using the default settings (where it is relativeToWorkspaceRoot). Then, when you make changes, the diagnostics are triggered again - but this time using relativeToRequire.

**Comment by JohnnyMorganz** [comment] 2023-12-24 18:25
I actually tried this out on vscode and i don't see these kinds of error messages every. Going to close this for now. If you still experience it, feel free to reopen, but it is more likely something weird in your custom editor

**Closed by JohnnyMorganz** 2023-12-24 18:25 UTC
Labels: bug

**Comment by itsfrank** [comment] 2024-04-05 19:15
I think I am running into this issue on neovim using [lopi-py/luau-lsp.nvim](https://github.com/lopi-py/luau-lsp.nvim)

Here is my config:
```lua
require("luau-lsp").setup({
    server = {
        filetypes = { "luau", "lua" },
        capabilities = default_capabilities,
        on_attach = default_on_attach, -- just sets up my lsp keymaps
        sourcemap = {
            enable = false,
        },
        settings = {
            ["luau-lsp"] = {
                require = {
                    mode = "relativeToFile",
                    directoryAliases = {
                        ["@lune"] = "~/.lune/.typedefs/0.8.2/",
                    },
                },
            },
        },
    },
})
```

Here is a video of the issue, notice that when I first open the file, I get errors, and type hints don't work. However after some edits the problem gets fixed. Then if I restart the lsp with `:LspRestart` the errors return.

https://github.com/JohnnyMorganz/luau-lsp/assets/7297152/4b2066c7-0e42-4a9b-8fad-c47047efc3a3

**Comment by itsfrank** [comment] 2024-04-05 23:11
Seems like this is an issue with neovim, I was pointed to this issue as the cause:  https://github.com/neovim/neovim/issues/26926

The command `:e %` fixes the issue, I have this (very ugly) workaround that makes the error pop up once per neovim session and automatically fix itself after I open the first luau file:

```lua
local run_once = false
require("luau-lsp").setup({
    server = {
        filetypes = { "luau", "lua" },
        on_attach = function(client, bufnr)
            default_on_attach(client, bufnr)
            if run_once then
                return
            end
            run_once = true
            vim.defer_fn(function()
                vim.cmd("e %")
            end, 500)
        end,
    },
})
```
