### ISSUE TITLE
There should be an option to place the cursor inside the autocompleted brackets

### ISSUE THREAD

**Issue by LEEROY-4** [JohnnyMorganz/luau-lsp#675] opened 2024-07-09 17:31 UTC
So option to go from this `wait()|` to this `wait(|)`

**Comment by JohnnyMorganz** [comment] 2024-07-13 11:01
This does exist already, but it seems like it doesn't work for `wait()`. It must be because the parameter for `wait` is optional.

**Comment by lolmanurfunny** [comment] 2024-07-13 23:23
> It must be because the parameter for wait is optional. 

Yep. It appears that this occurs when a parameter is typed as `any`, `unknown` or optional - in other words, if the type is `any` or unioned with `nil`. The cursor will only include up to the last parameter that doesn't satisfy the aforementioned criteria (see images 1 & 2).

![image](https://github.com/user-attachments/assets/ac983701-42c9-457d-ac82-dbd885c85586)

![image](https://github.com/user-attachments/assets/87378895-47fb-4da6-8c63-f1e8c3841a11)

Also, for user-defined functions, a workaround for this is to use generics, although this is only practical to do if the parameter would've otherwise been typed as `any` or `unknown`.

![image](https://github.com/user-attachments/assets/949f560d-5945-4410-9364-499842804013)

**Comment by JohnnyMorganz** [comment] 2024-11-10 12:38
This is actually a duplicate of #317

**Closed by JohnnyMorganz** 2024-11-10 12:38 UTC
