### ISSUE TITLE
Incorrect syntax highlight of a paren inside a quoted string

### ISSUE THREAD

**Issue by matthargett** [JohnnyMorganz/luau-lsp#287] opened 2023-02-06 19:31 UTC
![image](https://user-images.githubusercontent.com/1550766/217066968-87205f5c-a402-42ca-87b7-29a9df654c60.jpeg)

**Comment by JohnnyMorganz** [comment] 2023-02-09 13:27
I couldn't reproduce this 
![image](https://user-images.githubusercontent.com/19635171/217825551-8ed0c334-7d83-4154-963e-64d386358d5b.png)

**Comment by JohnnyMorganz** [comment] 2023-04-14 18:20
Closing this as cannot reproduce. I think it is a theming issue (works fine in default theme)

**Closed by JohnnyMorganz** 2023-04-14 18:20 UTC
Labels: bug
