### ISSUE TITLE
LSP instantly crashes when line of code is processed

### ISSUE THREAD

**Issue by techs-sus** [JohnnyMorganz/luau-lsp#451] opened 2023-08-19 17:41 UTC
While developing, I noticed that the LSP would crash if I overwrote Instance.

Reproduce:
```lua
-- even if it's global it will still crash lsp
local Instance = {
  new = function() end
}
```

**Comment by techs-sus** [comment] 2023-08-19 17:46
Workaround for now is to use getfenv(). Instance.new instead.

**Comment by JohnnyMorganz** [comment] 2023-08-24 00:56
I could not reproduce a crash with this sample. Do you have a larger reproduction?

**Comment by techs-sus** [comment] 2023-08-24 00:59
I was also directly editing Instance.new as a property, but sometimes even function calls crashed the lsp. In general, using Instance.new for purposes other then calling it might be problematic. If it helps, I am using helix editor.

**Comment by JohnnyMorganz** [comment] 2023-08-24 01:56
Your crashes may be related to this issue: https://github.com/Roblox/luau/issues/1017
What happens if you try disabling the `LuauTransitiveSubtyping` FFlag?

**Comment by JohnnyMorganz** [comment] 2023-08-26 15:42
Should be fixed in next release where we have updated Luau

**Closed by JohnnyMorganz** 2023-08-26 15:42 UTC
Labels: bug
