### ISSUE TITLE
VSCode LSP plugin crashes for no apparent reason after the 1.30.0 release.

### ISSUE THREAD

**Issue by snowcliffx** [JohnnyMorganz/luau-lsp#657] opened 2024-06-23 17:40 UTC
![image](https://github.com/JohnnyMorganz/luau-lsp/assets/135154876/b15305f5-0304-4611-be2a-5fb29ff3f35a)
![image](https://github.com/JohnnyMorganz/luau-lsp/assets/135154876/b3991aed-c78a-4ae3-99a0-785d431db03a)

**Comment by JohnnyMorganz** [comment] 2024-06-23 18:57
Do you have any repro steps for this crash? Also can you set `luau.server.trace` to messages and send the logs

**Comment by snowcliffx** [comment] 2024-06-23 20:26
> Do you have any repro steps for this crash? Also can you set `luau.server.trace` to messages and send the logs

No, not really. All I did was update the extension and suddenly it started almost immediately crashing whenever I opened an instance of VSCode. I've tried everything I could think of but the problem persists. Here are the logs with `luau.trace.server` set to messages.

[4-Luau Language Server.log](https://github.com/user-attachments/files/15945898/4-Luau.Language.Server.log)

I've checked, and the problem also persists on new projects.

**Comment by JohnnyMorganz** [comment] 2024-06-23 21:24
Sorry about that, I will try to resolve this when I have some time. Please downgrade to the previous version in the meantime

**Comment by JohnnyMorganz** [comment] 2024-06-24 17:40
I'm unable to repro this crash so far. Could you try disabling sourcemap support and trying again to see if it crashes? Please also send the logs

**Comment by alastairbarron** [comment] 2024-06-24 20:16
Hiya, I'm having a similar-looking problem. Tried disabling sourcemaps and still got this:

[1-Luau Language Server.log](https://github.com/user-attachments/files/15960833/1-Luau.Language.Server.log)

If I downgrade it works fine with sourcemaps enabled. Good luck fixing :)

**Comment by JohnnyMorganz** [comment] 2024-06-24 20:30
I found the bug related to sourcemaps which should be fixed in 1dfbc66

I've generated a new nightly release at https://github.com/JohnnyMorganz/luau-lsp/actions/runs/9651994809 which should build in ~20 mins. Please try installing the generated .vsix and seeing if you still experience crashes.

**Comment by JohnnyMorganz** [comment] 2024-06-24 20:31
@alastairbarron if you still experience crashes, could you set `luau.trace.server` to `verbose` or `messages` then send the logs? (Note that verbose can contain source code about your project, so please clean out anything sensitive. Messages will only include paths)

**Comment by alastairbarron** [comment] 2024-06-25 08:53
Hiya :) I installed from the nightly release and appear to still be getting the same problem. Here are the verbose logs: 

[3-Luau Language Server.log](https://github.com/user-attachments/files/15967799/3-Luau.Language.Server.log)

Thanks!

**Comment by snowcliffx** [comment] 2024-06-25 14:46
Sorry for the late response. I installed the nightly build and made a whole new rojo project, now I'm getting different results depending on what I set for sourcemaps. All of the below are with `luau.trace.server` set to `verbose`.

Here's what I get with sourcemaps enabled:
[4-Luau Language Server.log](https://github.com/user-attachments/files/15973170/4-Luau.Language.Server.log)

And here's what I get with sourcemaps disabled:
[5-Luau Language Server.log](https://github.com/user-attachments/files/15973184/5-Luau.Language.Server.log)
[6-Luau Language Server.log](https://github.com/user-attachments/files/15973185/6-Luau.Language.Server.log)

Yes, I get two separate logs when I set sourcemaps to disabled, which is also what happens if I don't have a rojo project at all and try to edit a .lua/.luau file.

**Comment by NobleDraconian** [comment] 2024-06-26 00:30
Downgrading to `v1.29.1` has stopped the crashing for me, the latest release was causing crashes for me as well.

**Comment by PomboDev** [comment] 2024-06-27 19:34
I have tested the latest [nightly](https://github.com/JohnnyMorganz/luau-lsp/actions/runs/9702022293) `1.30.1` build on Windows 11 here are my logs.

Verbose Log with Sourcemaps Enabled
[7-Luau.Language.Server.log](https://github.com/user-attachments/files/16020154/7-Luau.Language.Server.log)

Verbose Log with Sourcemaps Disabled
[8-Luau.Language.Server.log](https://github.com/user-attachments/files/16020178/8-Luau.Language.Server.log)

Messages Log with Sourcemaps Enabled
[9-Luau.Language.Server.log](https://github.com/user-attachments/files/16020199/9-Luau.Language.Server.log)

Messages Log with Sourcemaps Disabled
[10-Luau.Language.Server.log](https://github.com/user-attachments/files/16020233/10-Luau.Language.Server.log)

**Comment by JohnnyMorganz** [comment] 2024-06-27 19:54
Appreciate you trying it out! These logs are somewhat surprising, i am very much confused on what could be tripping it up

**Comment by JohnnyMorganz** [comment] 2024-06-27 20:16
Ok, the only thing that I can think of left. Please can you try the new nightly release: https://github.com/JohnnyMorganz/luau-lsp/actions/runs/9702934716

**Comment by OctoShotG** [comment] 2024-06-29 05:12
Hello, how exactly are you supposed to install extensions through the .vsix? When using the plugin through the Install from VSIX option in extensions still getting this log
[2-Luau Language Server.log](https://github.com/user-attachments/files/16038801/2-Luau.Language.Server.log)

**Comment by glomdom** [comment] 2024-06-29 21:24
Hey, I'm getting the same issue. I'm using the nightly release (https://github.com/JohnnyMorganz/luau-lsp/actions/runs/9702934716).

Here are the logs, with verbose tracing.

[log.txt](https://github.com/user-attachments/files/16042217/log.txt)

**Comment by JohnnyMorganz** [comment] 2024-06-30 08:38
Hey folks, still unable to track down the issue unfortunately.

I have another nightly release with some more trace debugging lines: https://github.com/JohnnyMorganz/luau-lsp/actions/runs/9730580051

This printf debugging isn't really working though, and I can't reproduce the crashes myself. I've started to ship debug symbols in the nightly release, so if anyone would be interested in trying to attach a debugger to find the crash stack trace, it would be immensely helpful

**Comment by glomdom** [comment] 2024-06-30 09:03
I fixed my issue by installing [vc_redist x64](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022). Seems like it was just a user problem and not a problem with luau-lsp.

**Comment by snowcliffx** [comment] 2024-06-30 11:55
> I fixed my issue by installing [vc_redist x64](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022). Seems like it was just a user problem and not a problem with luau-lsp.

Well, this is interesting. Although I had already installed it previously, it seems like "repairing" it fixed the problem. It wasn't an issue with luau-lsp for sure, but I also wonder why this caused the issue. Anyway, if anyone else is encountering the same problem, installing/repairing vc_redist is the fix.

**Comment by vladmarica** [comment] 2024-06-30 13:51
> I fixed my issue by installing [vc_redist x64](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022). Seems like it was just a user problem and not a problem with luau-lsp.

This also fixed the crash for me on Windows 11. I'm curious how you discovered this fix.

**Comment by JohnnyMorganz** [comment] 2024-06-30 16:07
Wow great find, this is looking like the problem. I've been struggling on this for so long. Thank you!

I think i might know the cause of why we started depending on the vc redistributable. Maybe I can get rid of that dependency

**Comment by Daw588** [comment] 2024-06-30 20:34
Perhaps you could make the program check for dependency if that is possible, and when it is found to be missing, the extension could ask the user whether they would like to have the extension download the dependency for them.

**Comment by JohnnyMorganz** [comment] 2024-07-01 17:40
This should be resolved in new release v1.31.0. https://github.com/JohnnyMorganz/luau-lsp/releases/tag/1.31.0 If you still experience issues, let me know!

**Comment by OctoShotG** [comment] 2024-07-02 05:47
Hello, this is still crashing. 
[log.log](https://github.com/user-attachments/files/16062299/log.log)

**Closed** 2024-07-06 10:15 UTC
Labels: bug

**Comment by JohnnyMorganz** [comment] 2024-07-13 08:46
This should be fixed for real in the next release. Thanks!

**Comment by JohnnyMorganz** [comment] 2025-03-16 14:53
Hey @AnimalCarrot206. From your logs it looks like you have a path with non-ASCII characters.

Unfortunately the language server doesn't handle those well right now (#746). Could you try renaming the folder?

**Comment by AnimalCarrot206** [comment] 2025-03-18 15:33
Hello again! I tried and it worked! Thanks for helping!
