### ISSUE TITLE
Request textDocument/* failed error popups when typing

### ISSUE THREAD

**Issue by cyrus01337** [JohnnyMorganz/luau-lsp#546] opened 2024-02-03 07:52 UTC
When typing using the latest extension version, I receive various `Request textDocument/* failed` error popups as shown below.

![image](https://github.com/JohnnyMorganz/luau-lsp/assets/63274991/ef08d324-40dd-4a4e-9593-abead81d9567)

Output shows:
```
[Error - 7:49:19 AM] Request textDocument/foldingRange failed.
  Message: invalid string position
  Code: -32603 
[Error - 7:49:19 AM] Request textDocument/semanticTokens/full failed.
  Message: invalid string position
  Code: -32603
```

If anything else is needed, let me know.

**Comment by cyrus01337** [comment] 2024-02-03 07:59
Rojo wasn't running on my studio instance, once connected this issue auto-resolves.

While this isn't the issue, I think it would be nice to maybe check for this and receive a more readable error _if feasible_.

**Comment by JohnnyMorganz** [comment] 2024-02-03 09:08
It's a bug. Do you have a reproducible example? Unfortunately the C++ exception doesn't give any further information in that error message, so I don't know what and why it gets hit.

**Comment by lolmanurfunny** [comment] 2024-02-04 01:39
Moving mountains of code with alt + up/down is currently the best repro strategy.

**Comment by JohnnyMorganz** [comment] 2024-02-04 10:07
I just tried moving some code using alt up/down, and it did not produce the error

**Comment by lolmanurfunny** [comment] 2024-02-04 11:10
It's just what I'm usually doing prior to its occurrence, so YMMV.

My friend found a repro.

https://github.com/JohnnyMorganz/luau-lsp/assets/77128366/826ad4aa-1d06-4e05-a325-34eb107abeb7

**Comment by JohnnyMorganz** [comment] 2024-02-04 11:44
Can you set `"luau.trace.server": "verbose"`, and then when this issue happens, send me the whole log?

I can't seem to be able to reproduce it directly.

**Comment by cyrus01337** [comment] 2024-02-27 05:20
Been super sick this whole month so my bad for not keeping tabs.

Attempted to reproduce to no avail, @lolmanurfunny is it possible for you/r friend to do so?

**Comment by JohnnyMorganz** [comment] 2024-06-02 15:23
Going to close this issue for now since there are no repro steps. If you experience it again, please feel free to reopen

**Closed by JohnnyMorganz** 2024-06-02 15:23 UTC
Labels: bug
